### ISSUE TITLE
feature: provide a topgit recognized bash entry to filter branch when do tg update 

### ISSUE THREAD

**Issue by LinBoLen** [mackyle/topgit#10]
- topgit working on top on original git. lots of conflict need to be solved
- provide bash entry to do some file transform to reduce conflict. lots of refactor can be done by script.
- if not use bash entry. can provide a yaml defined script. just like travis ci grammer. it can be simple provide bash execute tag. such as when do update. when do add depend.

the name of file maybe `.topgit.yml`

**Comment by mackyle** [comment]
Perhaps you could provide an example of what you're trying to accomplish?

**Comment by LinBoLen** [comment]
I can't remember that the scenario i need it.
